#! /usr/bin/env bash

# hacky as fuuuuuuuuu 

while read p ; do export $p; done < .test_env
mongo --eval "db.organizations.remove(); db.organizations.insert({name: \"test\", key: \"test-key\"})" marionapitest
supervisor app.js &
PID=$!
sleep 1 && mocha --bail
sleep 3 && kill $PID # ugh
